permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: CI
jobs:
  macos-homebrew-check:
    if: false # see: https://github.com/xmake-io/xmake-repo/issues/3316
    runs-on: macos-14
    name: Check on macOS / Homebrew
    steps:
      - name: Install Homebrew
        run:
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
      - name: Install deps
        run: brew install opencv xmake
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: xmake build -vD -y
         
  macos-xrepo-check:
    runs-on: macos-14
    name: Check on macOS / Xrepo
    steps:
      - name: Install Homebrew
        run:
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
      - name: Install deps
        run: brew install xmake
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: xmake build -vD -y

  windows-mingw-xrepo-check:
    runs-on: windows-latest
    name: Check on Windows / mingw / Xrepo
    steps:
      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Set up MinGW
        uses: e-t-l/setup-mingw@patch-1
        with:
          platform: x64
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: xmake build -vD -y