permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: CI
jobs:
  macos-homebrew-check:
    runs-on: macos-14
    name: Check on macOS / Homebrew
    steps:
      - name: Install Homebrew
        run:
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
      - name: Install opencv
        run: brew install opencv
      - name: Install xmake
        run: brew install xmake
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: xmake build -vD
  macos-xrepo-check:
    runs-on: macos-14
    name: Check on macOS / Xrepo
    steps:
      - name: Install Homebrew
        run:
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
      - name: Install xmake
        run: brew install xmake
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: xmake build -vD -y